# Generated by Django 6.0.5 on 2026-05-09 07:43

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niches', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, help_text='e.g. ["beauty", "food", "tech"]')),
                ('theme', models.CharField(choices=[('clean', 'Clean'), ('bold', 'Bold'), ('warm', 'Warm'), ('midnight', 'Midnight')], default='clean', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('rate_card', models.JSONField(blank=True, default=dict, help_text='{"deliverables": [{"type": ..., "rate": ..., "notes": ...}]}')),
                ('custom_links', models.JSONField(blank=True, default=list, help_text='[{"title": ..., "url": ..., "icon": ...}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('video_embed', 'Video embed'), ('video_upload', 'Video upload'), ('image', 'Image')], max_length=20)),
                ('original_url', models.URLField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('platform_source', models.CharField(blank=True, choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('facebook', 'Facebook')], max_length=20)),
                ('embed_html', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('video_title', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('facebook', 'Facebook')], max_length=20)),
                ('handle', models.CharField(max_length=100)),
                ('profile_url', models.URLField()),
                ('followers', models.PositiveIntegerField(default=0)),
                ('avg_views', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'platform', 'handle')},
            },
        ),
    ]
