# Generated by Django 6.0.5 on 2026-05-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_customlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='media_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='original_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
