# Generated by Django 6.0.5 on 2026-05-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0003_alter_portfolioitem_media_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
