# Generated by Django 6.0.5 on 2026-05-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0004_alter_socialaccount_options_socialaccount_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='theme',
            field=models.CharField(choices=[('clean', 'Clean'), ('bold', 'Bold'), ('warm', 'Warm'), ('midnight', 'Midnight'), ('cover', 'Cover')], default='clean', max_length=20),
        ),
    ]
