# Generated by Django 6.0.5 on 2026-05-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0007_alter_creatorprofile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='theme',
            field=models.CharField(choices=[('clean', 'Clean'), ('bold', 'Bold'), ('warm', 'Warm'), ('midnight', 'Midnight'), ('cover', 'Cover'), ('indigo', 'Indigo'), ('honey', 'Honey'), ('azure', 'Azure')], default='clean', max_length=20),
        ),
    ]
