# Generated by Django 6.0.5 on 2026-05-09 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Lowercase letters, digits, underscores, and dots. Used in /@username URLs.', max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Username may only contain lowercase letters, digits, underscores, and dots.', regex='^[a-z0-9_.]+$')]),
        ),
    ]
